version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Zurich"
    target-branch: "main"
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # PNPM uses 1440 minutes (1 day) since v11 to prevent downloading compromised packages
    cooldown:
      default-days: 2
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Zurich"
    target-branch: "main"
    rebase-strategy: "auto"
    commit-message:
      prefix: "ci"
      include: "scope"
    cooldown:
      default-days: 7
    groups:
      actions-dependencies:
        patterns:
          - "*"
