const SECONDS_PER_MINUTE = 60
const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * 60
const SECONDS_PER_DAY = SECONDS_PER_HOUR * 24

export const AUTH_CONFIG = {
  SESSION_EXPIRES_IN: SECONDS_PER_DAY * 7, // 7 days
  SESSION_UPDATE_AGE: SECONDS_PER_DAY, // 24 hours
  COOKIE_CACHE_MAX_AGE: SECONDS_PER_MINUTE * 5, // 5 minutes
  RATE_LIMIT_WINDOW: SECONDS_PER_MINUTE, // 1 minute window
  RATE_LIMIT_MAX: 30, // 30 requests per window
} as const
